### ISSUE TITLE
Offer .gz and .br compression simultaneously

### ISSUE THREAD

**Issue by dilyanpalauzov** [kryops/rollup-plugin-gzip#10]
I want to compress a file with gz and with brotli, so that browsers with brotli support get the .br file and the others get the .gz file.

Please provide an example with the shortest possible syntax that provides both brotli and .gz output from the same input.

**Comment by kryops** [comment]
Interesting use case, I haven't thought of that before...

Have you tried adding the plugin twice to your build config? One instance to generate gz, and the other one for brotli. It might look something like this:

```js
import { compress } from 'brotli'
import gzipPlugin from 'rollup-plugin-gzip'

const commonGzipPluginOptions = {
  // ...
}

// ...
    plugins: [
        gzipPlugin(commonGzipPluginOptions),
        gzipPlugin({
            ...commonGzipPluginOptions,
            customCompression: content => compress(Buffer.from(content)),
            fileName: '.br',
        }),
    ],
```

**Comment by dilyanpalauzov** [comment]
Yes, that works.  But I ask you to update the documentation and recommend this config.
