### ISSUE TITLE
Offer conditional exports in package.json

### ISSUE THREAD

**Issue by dilyanpalauzov** [kryops/rollup-plugin-gzip#12]
Per https://github.com/rollup/rollup/commit/7eea04afee0225e57b3c7fb9541560b11fc160cc#commitcomment-38163059 rollup reads from the plugins the main: "./dist/index.js" file.  If the package.json provides conditional imports in NodeJS terms, then rollup will read the ES6 modules instead

**Comment by kryops** [comment]
Released in v2.4.0
