### ISSUE TITLE
Substitutig node-zopfi-es with @gfx/zopfli

### ISSUE THREAD

**Issue by dilyanpalauzov** [kryops/rollup-plugin-gzip#13]
Here is an example using zopfi but from @gfx/zopfli instead of node-zopfi-es.  The advantage of the former is that it does not depend on node-gyp and the disadvantage of the latter is that it takes very, very long on every `yarn update`.

```javascript
import { gzipAsync } from '@gfx/zopfli';

… gzipPlugin({
  customCompression: content => gzipAsync(Buffer.from(content), {numiterations: 15}),
  })
```

**Comment by kryops** [comment]
hi @dilyanpalauzov , thanks for all your suggestions, I tried to add them to the README :blush:

**Comment by dilyanpalauzov** [comment]
For @gfx/zopfli the readme does not clarify that gzipAsync() must be used.  It took me a lot of time to figure this out myself.

**Comment by kryops** [comment]
:flushed: of course you're right - my `node-zopfli` example was wrong already as their `gzip` function takes a callback as well. Only they provide a `gzipSync` alternative while `@gfx/zopfli` provides a `gzipAsync` alternative :roll_eyes:
