### ISSUE TITLE
sourcemap: "hidden" not supported contrary to docs

### ISSUE THREAD

**Issue by Neilos** [kryops/rollup-plugin-gzip#21]
According to the documentation regarding the output.sourcemap option (https://rollupjs.org/configuration-options/#output-sourcemap),

> If true, a separate sourcemap file will be created. If "inline", the sourcemap will be appended to the resulting output file as a data URI. "hidden" works like true except that the corresponding sourcemap comments in the bundled files are suppressed.

However, if the `sourcemap: "hidden"` option is used, it still generates a sourceMappingUrl in the gzipped javascript file. 
Foe example, in vite configuration:
```
import gzipPlugin from "rollup-plugin-gzip";

export default defineConfig({
  resolve: { .. },
  plugins: [
    gzipPlugin(),
  ],
  build: {
    rollupOptions: {
      output: {
        sourcemap: "hidden" // prevent sourceMappingUrl in output and gzipped output files ????
      }
    }
  },
  server: { ... }
  ...
});

```

The URL is not "suppressed"

https://github.com/kryops/rollup-plugin-gzip/blob/18e24be50d1b7abd36d76af49d1a530d392e646e/src/index.ts#L102

`sourcemap: "inline"` is the only considered option: https://github.com/kryops/rollup-plugin-gzip/blob/18e24be50d1b7abd36d76af49d1a530d392e646e/src/index.ts#L104. 
The hidden option is unusable.

**Comment by kryops** [comment]
Hi @Neilos,

thanks for your report.

This plugin actually predates the `sourcemap: "hidden"` option in `rollup`, I just never noticed it was added there :sweat_smile: 

Should be fixed in v3.1.2
