### ISSUE TITLE
Provide an example with zopfli

### ISSUE THREAD

**Issue by tkrotoff** [kryops/rollup-plugin-gzip#4]
Could you provide an example with zopfli and rollup-plugin-gzip v2 inside README.md

**Comment by kryops** [comment]
Hi @tkrotoff,

do you need a special setup to get node-zopfli working or is there some secret, or even a better maintained alternative package? (I run Node 10 on Linux)

One of the reasons why I removed the built-in zopfli support in v2 was that I couldn't get it to work on my machine any more, and the node-zopfli project seems to be unmaintained in general.

According to the docs, it should work somehow like this:

```ts
import { gzip } from 'node-zopfli'
import { rollup } from 'rollup'
import gzipPlugin from 'rollup-plugin-gzip'

rollup({
    input: 'src/index.js',
    plugins: [
        gzipPlugin({
            customCompression: content => new Promise((resolve, reject) => {
                gzip(
                    // content could be a string but node-zopfli might only accept buffers
                    Buffer.from(content),
                    { /* zopfli options */ },
                    (err, result) => {
                        if (err) reject(err)
                        else resolve(result)
                    }
                )
            }),
        }),
    ],
}).then(/* ... */)
```

Could you check if this works for you before I add it to the README? :smile:

**Comment by tkrotoff** [comment]
This works:

```JS
import { gzip as zopfli } from 'node-zopfli';
import gzip from 'rollup-plugin-gzip';

// ...

    gzip({ customCompression: content => zopfli(Buffer.from(content)) })

// ...
```

I don't understand your TypeScript typings:
```TypeScript
CustomCompressionOption = (content: string | Buffer) => string | Buffer | Promise<string | Buffer>
```

Why would `content` be a `string` *or* a `Buffer`? It is a ~~`Buffer`~~ `string`: `zopfli(Buffer.from(content))` works, `zopfli(content)` doesn't

**Comment by kryops** [comment]
Ah, I didn't notice that `node-zopfli` already returns a promise, that makes things easier :)

The "string of buffer" type comes from rollup's own typings:

https://github.com/rollup/rollup/blob/b67bf5b85042583dcee2726f68ac47df5d071e60/src/rollup/types.d.ts#L355

I assume they use strings for JS chunks and CSS assets, and Buffers for binary assets like images.

Unlike the official `zlib` module, `node-zopfli` seems to only allow Buffers as input types, that's why you need the `Buffer.from()` here to convert the string chunks into Buffers.

**Comment by tkrotoff** [comment]
Sorry, I made a wording mistake in my previous comment:
> Why would `content` be a `string` or a `Buffer`? It is a ~`Buffer`~ `string`

I still don't understand how `content` in `CustomCompressionOption` could be `string | Buffer`. That makes no sense to me. It should be just `string`: is it `Buffer` on sundays and `string` on mondays? :-)

**Comment by tkrotoff** [comment]
I see, `additionalFiles` are treated as Buffer while classic rollup bundling are string. The test 'with additionalFiles option' is the only one that uses Buffer.

How to test: add `console.log('typeof content:', typeof fileContent)` and/or `if (typeof fileContent === 'object') throw new Error()` inside [compressGzip](https://github.com/kryops/rollup-plugin-gzip/blob/v2.0.0/src/index.ts#L139)

**Comment by kryops** [comment]
True, I didn't even think about the `additionalFiles`.
Also, this plugin adds its compressed `.gz` artifacts as `Buffer`s to the rollup bundle - other plugins that run before this one might do the same.
The `string | Buffer` type basically just means "your custom compression function should ideally be able to handle both strings and Buffers" - depending on your use case and configuration, it might only be strings :wink:

**Comment by tkrotoff** [comment]
@kryops 

> One of the reasons why I removed the built-in zopfli support in v2 was that I couldn't get it to work on my machine any more

I think I know why.
I've encountered this issue under macOS, `brew install node@8` gave me the solution:
```
If you need to have node@8 first in your PATH run:
  echo 'export PATH="/usr/local/opt/node@8/bin:$PATH"' >> ~/.bash_profile

For compilers to find node@8 you may need to set:
  export LDFLAGS="-L/usr/local/opt/node@8/lib"
  export CPPFLAGS="-I/usr/local/opt/node@8/include"
```

This is my `~/.bash_profile`:
```
export PATH="/usr/local/opt/node@8/bin:$PATH"
export LDFLAGS="-L/usr/local/opt/node@8/lib"
export CPPFLAGS="-I/usr/local/opt/node@8/include"
```
See the LDFLAGS and CPPFLAGS? that's the important part if you want to compile C/C++ code for Node.js
