### ISSUE TITLE
gzipPlugin is not a function

### ISSUE THREAD

**Issue by sumohammed** [kryops/rollup-plugin-gzip#6]
Hello,
Hope you doing well?

Whenever i try to build my project it fails with this error "gzipPlugin is not a function", it works only when i modify rollup-plugin-gzip/dis/index.js from exports.default = gzipPlugin to  module.exports = gzipPlugin. 

The problem am having is i use gitlabs pipeline to build my project and once npm installs the packages again the error continues.

Please help !!!!

**Comment by kryops** [comment]
@sumohammed could you provide your rollup config that is causing the problem?

At first glance, this looks like the "normal" though very annoying incompatibility between ES modules (which this plugin uses) and CommonJS modules (which Node uses). Are you importing this plugin via `require()`? If so, changing `require('rollup-plugin-gzip')` to `require('rollup-plugin-gzip').default` could do the trick.

**Comment by sumohammed** [comment]
super grateful bro, worked like a charm.

**Comment by kryops** [comment]
Glad I could help. I added a note about this to the README.

**Comment by Anoesj** [comment]
Just playing the devil's advocate here: why not just export as a named export?
Most people still use the CommonJS notation in Node, so this seems a little silly.

**Comment by kryops** [comment]
@Anoesj I know, it's sad that this is still a problem.

While I usually prefer named exports to default exports, this seems to be kind of a convention for Rollup. Both the docs on [using plugins](http://rollupjs.org/guide/en/#using-plugins) and [plugin development](http://rollupjs.org/guide/en/#a-simple-example) use ESM default exports.

Adding a named export would at least allow all of these import syntaxes:
```
import gzipPlugin from 'rollup-plugin-gzip';
import { gzipPlugin } from 'rollup-plugin-gzip';
const { gzipPlugin } = require('rollup-plugin-gzip');
```

But to get the good old `const gzipPlugin = require('rollup-plugin-gzip')`, I would need to write a  post-build script to change my transpiled output, TypeScript does not seem to have an option to create CommonJS-compatible default exports.
